rework dogfooding logix for new plugin naming part 7

diff --git a/.github/workflows/pr-core-tests.yml b/.github/workflows/pr-core-tests.yml
--- a/.github/workflows/pr-core-tests.yml
+++ b/.github/workflows/pr-core-tests.yml
@@ -91,13 +91,8 @@ jobs:
         run: |
           mkdir -p /home/runner/.lando/plugins/@lando
           ln -sf /home/runner/work/core/core /home/runner/.lando/plugins/@lando/core
-          lando --clear
-          lando version
-          lando config --path plugins
-          echo "hi"
-          lando config --path plugins --format json | jq -r '.[] | select(.name == "@lando/core")'
-          echo "hi2"
           lando config --path plugins --format json | jq -r '.[] | select(.name == "@lando/core").searchDir' | grep /home/runner/.lando/plugins/@lando/core || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
+          lando config --path plugins --format json | jq -r '.[] | select(.name == "@lando/networking").searchDir' | grep /home/runner/.lando/plugins/@lando/core/plugins/networking || (echo "::error:: Not dogfooding this plugin correctly!" && exit 1)
       - name: Run Leia Tests
         uses: lando/run-leia-action@v2
         env:
